### ISSUE TITLE
Request for Feedback (SRS)

### ISSUE THREAD

**Issue by Tan630** [Tan630/Agolearn#30]
Edited SRS document is attached. [SRS_Edit.pdf](https://github.com/Tan630/Agolearn/files/14729774/SRS_Edit.pdf). Red text marks changes. Everything has been changed.

The following sections describe changes corresponding comments in prior feedback:

### Reference
Move template source and style reference to end of document

### Proper Citation
Add citations using a citation manager

### Specificity of Goal Statements and Assumptions, including Properties of a Correct Solution
Complete rework. Now, goals decompose the problem into achievable objectives, then requirements decompose goals into actionable (and testable) items.

### Requirements
Complete rework.

### Rationale
Complete rework. Add considerations while writing the requirement documentation.

### Likely and Unlikely Changes
Mark these sections as not applicable.

### Traceability
Add traceability information, specify types of dependency ("derivation").

### Removed Sections
Return **System Constraints** and **Rationales** with content. Return all sections as Not Used. Still, user responsibilities and system responsibilities are removed.

**Comment by smiths** [comment]
Given the constraints on my time, I have to prioritize grading the MG+MIS documents for the class before looking at the revisions to previous documents.

**Comment by smiths** [comment]
I've had a quick look at your SRS.  I thought some quick feedback would be useful for you.  There is a definite improvement from the previous version.  You've obviously put some considerable time and effort into thinking about this project.  However, there are still some inconsistencies with the template, as follows:

- the goal statements are supposed to be nonfunctional.  Your nonfunctional goals should be stated as requirements.
- the goal statement should characterize what is being calculated.  The goal is to optimize.  Given a function, return the optimum value.  You might also want an initial value, a range in which to search, the value of the parameters at the optimum.  The goal statement should be a simple, easy to understand, statement of what the library will be used to do.  You can write this abstractly because you are allowing variation of the function.  I believe your function is even generic in terms of the types of its arguments.  I think the type of the output has to be real though (right?).  If not real, it at least has to be an ordered type.
- your IM 1 doesn't actually say to optimize.  I think you are thinking too much about the quality of the solution in this model.  The model is intended to find the maximum.  The quality of this solution is captured by the nonfunctional requirements, where you admit that accuracy is not guaranteed.
- I don't see any of the theory of evolutionary algorithms.  Wasn't that in the previous draft?  The information in your terminology section is not actually used in the document.  The terminology looks to me like the theoretical models you should be defining.

**Comment by Tan630** [comment]
These are good points. I plan to make the following changes:
1. Remove goals that derive non-functional requirements. Reword some goals: for example, G 4 (ease of use) should become a functional goal: that the system instructs the implementation of software.
2. Reword non-functional requirements to functional requirements: for example, "independence from third-party modules" defines what the system does not do. It should be a functional requirement.
3. IM1 should be Iterative Optimization. The name "Optimization" is misleading
4. Add blurb about evolutionary learning

**Comment by Tan630** [comment]
Some non-functional requirements can also be constraints. For example, the requirement that the system does not depend on third-party libraries is learned during feasibility study and affects design. Classifying it as a constraint would be more appropriate.

**Comment by Tan630** [comment]
Resolve in part. Changes are marked in red in
[this file](https://github.com/Tan630/Agolearn/files/14796288/SRS-with-changes.pdf). I have made the following changes:

### Goals to System Constraints
Move some goals, especially those that directly follow expert advise, are system constraints. These goals (a) are set after literature review (feasibility study), (b) are source from experts (stakeholder requirement), and (c) match frameworks that enable state-of-the-art results (best practices), which makes them system constrains.

### Detach Goals from Non-Functional Requirements
Some NFRs do not necessarily source from goals; remove reference to goals for these requirements. One NFR does source from a goal. Change it to a FR.

### Enrich Introduction
Add blurb in **Introduction** to explain evolutionary learning learning.

**Comment by Tan630** [comment]
Resolve. Changes have been reviewed and approved. I think.
